lab7/myimgur/app/urls.py
from django.urls import path

from . import views

app_name = 'app'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:image_id>/', views.detail, name='detail'),
    path('<int:image_id>/comment', views.comment, name='comment'),
    path('like_comment/<int:comment_id>', views.like_comment, name='like'),
    path('<int:image_id>/upvote', views.upvote, name='upvote'),
    path('<int:image_id>/downvote', views.downvote, name='downvote'),
    path('new', views.create_image, name='create_image'),
    path('<int:image_id>/edit', views.edit_image, name='edit_image'),
    path('<int:image_id>/delete', views.delete_image, name='delete_image'),
    path('delete/<int:comment_id>',views.delete_comment, name='delete_comment'),
    path('approve_comment/<int:comment_id>', views.approve_comment, name='approve_comment'),
    path('edit/<int:comment_id>', views.edit_comment,name='edit_comment')
]

lab7/myimgur/imgur/urls.py
from django.contrib import admin
from django.urls import include,path
from app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('images/', include('app.urls')),
    path('', views.index, name='index'), 
]

lab7/myimgur/app/templates/includes/approve_button.html
<div>
  {% if user.is_superuser and comment.is_approved %}
  <form
    action="{% url 'app:approve_comment' comment.id %}"
    method="post"
    role="form"
    class="form-inline"
  >
    {% csrf_token %}
    <input type="submit" value="Approve" class="btn" />
  </form>
  {% endif %}
</div>

lab7/myimgur/app/templates/includes/bs4_form.html
{% load widget_tweaks %}
{% for hidden_field in form.hidden_fields %}
{{ hidden_field }}
{% endfor %}

{% if form.non_field_errors %}
<div class="alert alert-danger" role="alert">
  {% for error in form.non_field_errors %}
    {{ error }}
  {% endfor %}
</div>
{% endif %}

{% for field in form.visible_fields %}
<div class="row form-group">
  <div class="col-md-8 controls mx-auto">
    {{ field.label_tag }}

    {% if form.is_bound %}
      {% if field.errors %}
        {% render_field field class="form-control is-invalid" %}
        {% for error in field.errors %}
          <div class="invalid-feedback">
            {{ error }}
          </div>
        {% endfor %}
      {% else %}
        {% render_field field class="form-control is-valid" %}
      {% endif %}
    {% else %}
      {% render_field field class="form-control" %}
    {% endif %}

    {% if field.help_text %}
      <small class="form-text text-muted">{{ field.help_text }}</small>
    {% endif %}
  </div>
</div>
{% endfor %}

lab7/myimgur/app/templates/includes/delete_comment_button.html
  <a id="delete_{{ comment.id }}" href="#">Delete</a>
  <form id="delete_form_{{ comment.id }}" 
        method="post" 
        action="{% url 'app:delete_comment' comment.id %}"
        class="hidden"> 
        {% csrf_token %}
  </form>
  <script>
    $(document).on('click','#delete_{{ comment.id }}', function(){
      $('#delete_form_{{ comment.id }}').submit();
    });
  </script>

  

lab7/myimgur/app/templates/includes/delete_image_link.html
  <a id="delete_{{ image.id }}" href="#">Delete</a>
  <form id="delete_form_{{ image.id }}" 
        method="post" 
        action="{% url 'app:delete_image' image.id %}"
        class="hidden"> 
        {% csrf_token %}
  </form>
  <script>
    $(document).on('click','#delete_{{ image.id }}', function(){
      $('#delete_form_{{ image.id }}').submit();
    });
  </script>

  

lab7/myimgur/app/templates/includes/like_button.html
<div>
  {% if user.is_authenticated %}
  <form
    action="{% url 'app:like' comment.id %}"
    method="post"
    role="form"
    class="form-inline"
  >
    {% csrf_token %}
    <input type="submit" value="+" class="btn" />
  </form>
  <div class="vote-score">
    <span class="float-left"> {{ comment.like_score }} </span>
  </div>
  {% endif %}
</div>

lab7/myimgur/app/templates/includes/vote_buttons.html
<div> 
  {% if user.is_authenticated %}
    <form action="{% url 'app:upvote' image.id %}" 
    method="post" 
    role="form" 
    class="form-inline float-left">
      {% csrf_token %}
      <input type="submit" value="+" 
      class="btn {{ vote.upvote|yesno:'btn-success, btn-secondary' }}" />
    </form>
    <div class="vote-score">
      <span class="float-left">
        {{ image.vote_score }}
      </span>
    </div>
    <form action="{% url 'app:downvote' image.id %}" 
    method="post" 
    role="form" 
    class="form-inline float-left">
      {% csrf_token %}
      <input type="submit" value="-" 
      class="btn {{ vote.downvote|yesno:'btn-danger, btn-secondary' }}" />
    </form>
  {% endif %}
  </div>